name: Oneblock
main: Oneblock.Oneblock
version: 0.0.1
api-version: 1.13
author: YoshooDev
softdepend: [PlaceholderAPI, WorldGuard]
commands:
  oneblock:
    description: Oneblock main command.
    aliases: ob
    usage: /ob join
  ob j:
  ob ver:
    description: Version.
permissions:
  Oneblock.set:
    description: For admin
    default: op
  Oneblock.join:
    description: For all
    default: true
  Oneblock.invite:
    default: true
  Oneblock.ignoreBarrier:
    default: op
